### PR TITLE
PK readability improvements

### PR DESCRIPTION
**Pull request by peterkaminski**
Make a few readability improvements:

- flesh out README and make readability improvements
- add a few comments and readability changes to `chap.py` shim script
- rename `chap.py` shim to `chap-dev.py` to reduce potential confusion between shim and library

Not specifically for readability, but useful for people installing in development mode:

- add `/venv` to `.gitignore`

The changes in this PR don't have internal dependencies (except for one exception explained in the next paragraph). A subset of the changes (per commit, or even line-by-line) can be accepted or rejected without causing problems.

The dependency exception: in `chap-dev.py`, `sys.path.insert(0, ...` is used rather than `sys.path[0] = ...`, partly for readability, partly as a demonstration of best practice to developers not to overwrite one of the search path entries. If the shim is renamed back to `chap.py`, the `insert` will not overwrite `.`, and the script will try to import itself rather than the library.

Language note: since "commandline" is not a standard English word, I recommend separating them: "command line". It's customary to hyphenate compound adjectives, so when used to modify a noun such as "usage" or "arguments", it would be "command-line".

### CODE REVIEW

**Comment by peterkaminski** [comment]
"Test / pre-commit (pull_request)" (black) is failing, but I don't understand the test or why it's failing, I'm sorry.

I _think_ everything should work, and `./chap-dev.py` works fine locally.

If the fail is not a false positive and I should change something, please let me know.

**Comment by jepler** [comment]
Thanks! Black wants too change some white space. You can reproduce the failure locally (hopefully) by installing pre-commit via pip and then running `pre-commit run --all-files` (from memory)

Adding this to README would clearly be a good idea. I'm familiar with pre-commit but I think it's still pretty niche. And it may not run with the exact same settings just invoking black at the command line would (this looks like a difference of opinion about maximum line length, one of the few tunables in black)

**Comment by jepler** [comment]
Otherwise, looks good. Choosing a different name for the script sure reduces the chance of footguns .

**Comment by peterkaminski** [comment]
Thanks for the `pre-commit` tip, running it locally gave access to the modified file, which I committed. (Line length thing, it was a good change.)

Adding a note about `pre-commit` in the README at some point is a good idea.

**Comment by jepler** [comment]
Thank you! I'm mobile right now so feel free to add an issue calling for documentation of pre-commit!

**Comment by peterkaminski** [comment]
You beat me to it (#21)! Thanks. :-)

**Pull request merged**
