### PR TITLE
basic import from chatgpt

### PR DESCRIPTION
**Pull request by jepler**
This understands the format produced by https://github.com/pionxzh/chatgpt-exporter and exports every branch of the conversation to a separate chap session.

### CODE REVIEW

**Comment by peterkaminski** [comment]
I've tried `import` with various conversations exported with ChatGPT Exporter, and it works great.

The one small enhancement request I have: be able to specify an output path for the session file.  To use the same flags supported by `tui`, that might be `-n`:

```shell
chap import -n my_conversations/Bedtime_Story.json ~/Downloads/chatgpt-export-json-20230330/Bedtime_Story.json
```

But that's not needed to ship this PR, `import` works great and will be very helpful.

**Comment by jepler** [comment]
Thanks for testing! I just updated it with the ability to specify the output location (--output-directory) but not the filename itself. But since I also added importing every branch of the conversation it's not really possible to use a single filename...

**Comment by peterkaminski** [comment]
Importing all branches and specifying `-o` is great!

Don't let me slow you down, but wdyt:

- use the branch UUID instead of the timestamp for the output filename?
- future enhancement: optionally copy the original filename into the output filename (with timestamp or UUID appended)?

Just ideas, not demands. :)

**Comment by jepler** [comment]
now the output filename will be based on the input filename + branch uuid

and chatgpt sessions without a title will not cause an import error. I had at least one session without a title.

**Comment by peterkaminski** [comment]
Wow, perfect! 💯

**Pull request merged**
